### PR TITLE
Add Post-processing

### PR DESCRIPTION
**Pull request by cotepat**
Automatically call external post-process scripts before exporting G-Code

### CODE REVIEW

**Comment by 5axes** [comment]
Would be great to have an internal postprocess function based on a Python source code ( Same as in Cura) and not an external call as Superslicer or PrusaSlicer.
Pro : mutch mode easy to use and integrate by the user community.
Some postprocess script could be integrate in the software package and become some "Standard"

Cons : limited generaly to one langage (Python)

**Comment by SoftFever** [comment]
#10

**Comment by SoftFever** [comment]
@cotepat Thank you very much.
This is awesome.
LGTM, I will merge it.

**Comment by SoftFever** [comment]
@5axes external process is more flexible and powerful in this case. Imagine the post-processing script need a pip library ;)

**Comment by lbibass** [comment]
Post-Processing doesn't seem to work with [Klipper Estimator.](https://github.com/Annex-Engineering/klipper_estimator)

I'm not sure why.

**Comment by cotepat** [comment]
It does work for me : 

image

image

**Comment by lbibass** [comment]
I also get a "processed by klipper estimator" at the end of the gcode, but Fluidd doesn't report the same time that Klipper_estimator reports. 

```  Minimal time:                21m8.501s (1268.501s)```
Screenshot 2023-01-24 at 6 03 16 PM
Screenshot 2023-01-24 at 6 03 36 PM

**Comment by cotepat** [comment]
Ok I was able to replicate it... It has nothing to do with the addition of postprocess feature. But you are right klipper-estimator currently do not work with BambulabStudio. I will have a look at it. This should not be hard to fix!

**Comment by cotepat** [comment]
Ok I have a version that works... I made a specific pull request on this : https://github.com/SoftFever/BambuStudio-SoftFever/pull/229

**Pull request merged**
