### PR TITLE
New printer: TwoTrees SP-5 Klipper

### PR DESCRIPTION
**Pull request by behold81**
First working version of TwoTrees SP-5 running klipper. this can be the base to start using this slicer. most of the generic materials are OOTB ones and this profile is made for near stock printers just running klipper. roughtly running a max speed of 200mm/s and runs successfully

### CODE REVIEW

**Review by SoftFever — CHANGES_REQUESTED** [review]
Overall looks good to me.
Can you move the SP-5.png to `resources\web\image\printer` folder and rename it to `TwoTrees SP-5 Klipper_cover.png` ? So that the image can be displayed in the printer selection page.

**Comment by behold81** [comment]
Crap. Forgot I had done that already locally.  Will do. Send the pull request when done.

**Review by behold81 — COMMENTED** [review]
This is now corrected.

**Comment by SoftFever** [comment]
Thanks.
Merged.

**Pull request merged**
