### PR TITLE
Add Tronxy X5SA 400 Profile

### PR DESCRIPTION
**Pull request by erebus04**

### CODE REVIEW

**Comment by jeor112** [comment]
Thank you for looking into this!
I have made the changes as fare as I can see you have made and I still have the same issue, that the filament profiles don't show up.
I then have downloaded the latest version, removed the C:\Users\XXX\AppData\Roaming\BambuStudio-SoftFever folder to be sure, that it do not interferer with the new installation.
Installed the new version.
Copied the Tronxy folder and files from the old version.
It's the same issue with the new version.

Maybe something I have missed or maybe you are not done investering my messed up files?

Thanks in advance.

**Comment by jeor112** [comment]
Just to illustrate it:
image

**Comment by erebus04** [comment]
If I copy the tronxy profile I created into the folder and then select the printer, I have all the filament profiles to choose from.

Have you ever deleted the printer and the system folder and then recreated the printer?




***@***.***

***@***.***
Von: jeor112 ***@***.***>
Gesendet: Sonntag, 1. Januar 2023 11:45
An: SoftFever/BambuStudio-SoftFever ***@***.***>
Cc: erebus04 ***@***.***>; Author ***@***.***>
Betreff: Re: [SoftFever/BambuStudio-SoftFever] Add Tronxy X5SA 400 Profile (PR #81)


Just to illustrate it:
[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F14199833%2F210167981-dc8d58bd-cc74-431c-8139-b06174e73c36.png&data=05%7C01%7C%7Ca5c5adf4cdb04949635c08daebe5471f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638081667208448405%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=URJvzSMC7298UOAi5sua%2B5gZBlyvuq9eH3G4UH1ke%2Bs%3D&reserved=0>

-

**Comment by jeor112** [comment]
Yes, I have done as you suggested, but I have to addmit, that I haven't downloaded the profile that you have modified, so maybe I have missed something when scrolling through your files.
Again, sorry for my ignorance. Trying to learn. :-D 
How do I download your complete modified printer profile from this site? :-/

**Comment by erebus04** [comment]
You can wait until the merge into the main branch is done, or download from my repository.
https://github.com/erebus04/BambuStudio-SoftFever

**Comment by jeor112** [comment]
Ahh okay thanks!!

**Comment by jeor112** [comment]
Thank you very much! 
Ii's working now.
Like I mentioned, I must have missed something.
I really appreciate your help!

**Comment by erebus04** [comment]
I'm glad if it works.
You are welcome :)

**Comment by SoftFever** [comment]
Thanks, both of you, for working on it @erebus04 @jeor112 .
I noticed it uses `klipper` g-code flavor. 
I don't own a Tronxy X5SA 400, so I'd like to check whether it comes with Klipper preinstalled.

**Comment by erebus04** [comment]
The original firmware is Chitu.
There is now also Matlin firmware for the Tronxy
Sorry for the confusion.
I have adjusted the configuration and also added an addition in the printer selection with Marlin.

image

**Review by SoftFever — APPROVED** [review]

**Comment by SoftFever** [comment]
Hi @erebus04 and @jeor112 
Ref issue #108 
I've seen crashes too.
I have temporarily reverted this PR.
Would you like to retake a look at the profile?

**Comment by jeor112** [comment]
Same here on Windows.
The old "Klipper" version still works for me.

**Comment by erebus04** [comment]
I will check and revise the profile completely

**Pull request merged**
