### PR TITLE
fix 256px icon to big

### PR DESCRIPTION
**Pull request by hliebscher**
running app icon to big

### CODE REVIEW

**Comment by freejstnalxndr** [comment]
This was also fixed in my PR.

**Comment by hliebscher** [comment]
@freejstnalxndr 
if i use your PR testet 2 times  it crash the app during startup process MAC M1

**Comment by SoftFever** [comment]
@hliebscher Thanks!
It's hard to tell the change since I can't preview the file on GitHub.
Could you explain a little bit about what change you have made?

**Comment by SoftFever** [comment]
Saw it.
It's the margin.

**Pull request merged**
